lint-and-format.yml: workflow updated

diff --git a/.github/workflows/lint-and-format.yml b/.github/workflows/lint-and-format.yml
--- a/.github/workflows/lint-and-format.yml
+++ b/.github/workflows/lint-and-format.yml
@@ -25,8 +25,8 @@ jobs:
 
     - name: isort
       run: |
-        uv run isort app/ --check-only
-        uv run isort tests/ --check-only
+        uv run isort app/ --check-only; if [[ $? -eq 0 ]] && echo "SUCCESS" || echo "CHECK FAILED"
+        uv run isort tests/ --check-only; if [[ $? -eq 0 ]] && echo "SUCCESS" || echo "CHECK FAILED"
 
     - name: black
       run: |
@@ -35,5 +35,5 @@ jobs:
 
     - name: flake8 .
       run: |
-        uv run flake8 app/
-        uv run flake8 tests/
+        uv run flake8 app/; if [[ $? -eq 0 ]] && echo "SUCCESS" || echo "CHECK FAILED"
+        uv run flake8 tests/; if [[ $? -eq 0 ]] && echo "SUCCESS" || echo "CHECK FAILED"
